import { Agent, Client, Lead, Mission, Opportunity, OperationalItem, Site, Sop, TimeEntry } from '@/types'

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    company_id: 'company-1',
    first_name: 'Marie',
    last_name: 'Dupont',
    phone: '06 12 34 56 78',
    email: 'marie.dupont@example.com',
    specialty: 'Nettoyage bureaux',
    skills: ['nettoyage', 'désinfection'],
    business_registration_number: null,
    contract_type: 'cdi',
    weekly_availability_hours: 35,
    weekly_availability: { lundi: true, mardi: true, mercredi: true, jeudi: true, vendredi: true, samedi: false, dimanche: false },
    zone: 'Paris 8e',
    status: 'disponible',
    hourly_cost: 14,
    notes: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'agent-2',
    company_id: 'company-1',
    first_name: 'Jean',
    last_name: 'Martin',
    phone: '06 98 76 54 32',
    email: 'jean.martin@example.com',
    specialty: 'Vitrerie',
    skills: ['vitrerie', 'nettoyage haute pression'],
    business_registration_number: '123456789',
    contract_type: 'auto_entrepreneur',
    weekly_availability_hours: 20,
    weekly_availability: { lundi: true, mardi: false, mercredi: true, jeudi: false, vendredi: true, samedi: true, dimanche: false },
    zone: 'Paris 9e',
    status: 'disponible',
    hourly_cost: 18,
    notes: null,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'agent-3',
    company_id: 'company-1',
    first_name: 'Fatou',
    last_name: 'Diallo',
    phone: '07 11 22 33 44',
    email: 'fatou.diallo@example.com',
    specialty: 'Nettoyage industriel',
    skills: ['nettoyage industriel', 'produits chimiques'],
    business_registration_number: null,
    contract_type: 'cdd',
    weekly_availability_hours: 25,
    weekly_availability: { lundi: true, mardi: true, mercredi: false, jeudi: true, vendredi: true, samedi: false, dimanche: false },
    zone: 'Banlieue Nord',
    status: 'occupe',
    hourly_cost: 15,
    notes: null,
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-03-10T10:00:00Z',
  },
]

export const mockClients: Client[] = [
  {
    id: 'client-1',
    company_id: 'company-1',
    name: 'Groupe Immobilier Haussman',
    contact_name: 'Pierre Leblanc',
    email: 'contact@haussman.fr',
    phone: '01 23 45 67 89',
    billing_address: '123 Av. des Champs-Élysées',
    city: 'Paris',
    client_type: 'entreprise',
    status: 'actif',
    notes: 'Client premium, 3 immeubles',
    created_from_opportunity_id: null,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'client-2',
    company_id: 'company-1',
    name: 'Cabinet Médical Saint-Lazare',
    contact_name: 'Dr. Sophie Renard',
    email: 'cabinet@saint-lazare.fr',
    phone: '01 87 65 43 21',
    billing_address: '45 Rue Saint-Lazare',
    city: 'Paris',
    client_type: 'professionnel',
    status: 'actif',
    notes: null,
    created_from_opportunity_id: null,
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
]

export const mockSites: Site[] = [
  {
    id: 'site-1',
    company_id: 'company-1',
    client_id: 'client-1',
    name: 'Immeuble Champs-Élysées',
    address: '123 Av. des Champs-Élysées',
    city: 'Paris',
    surface_area: 1200,
    access_code: '1234A',
    access_instructions: 'Portail principal, badge remis au gardien',
    service_type: 'nettoyage_bureaux',
    frequency: 'quotidien',
    sop_id: 'sop-1',
    notes: null,
    created_from_opportunity_id: null,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'site-2',
    company_id: 'company-1',
    client_id: 'client-1',
    name: 'Parking Souterrain',
    address: '123 Av. des Champs-Élysées (sous-sol)',
    city: 'Paris',
    surface_area: 800,
    access_code: null,
    access_instructions: 'Accès depuis le hall B',
    service_type: 'nettoyage_parking',
    frequency: 'hebdomadaire',
    sop_id: null,
    notes: null,
    created_from_opportunity_id: null,
    created_at: '2026-01-25T10:00:00Z',
    updated_at: '2026-01-25T10:00:00Z',
  },
  {
    id: 'site-3',
    company_id: 'company-1',
    client_id: 'client-2',
    name: 'Cabinet médical - Salle attente + consultation',
    address: '45 Rue Saint-Lazare',
    city: 'Paris',
    surface_area: 150,
    access_code: '9876',
    access_instructions: 'Digicode entrée immeuble',
    service_type: 'nettoyage_medical',
    frequency: 'quotidien',
    sop_id: 'sop-2',
    notes: 'Désinfection renforcée zones consultation',
    created_from_opportunity_id: null,
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
]

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    company_id: 'company-1',
    company_name: 'Restaurant Le Gourmet',
    sector: 'Restauration',
    city: 'Paris 2e',
    email: 'contact@legourmet.fr',
    phone: '01 42 33 44 55',
    website: 'www.legourmet.fr',
    source: 'linkedin',
    ai_score: 85,
    probable_need: 'Nettoyage cuisine et salle quotidien',
    status: 'nouveau',
    notes: null,
    converted_opportunity_id: null,
    created_at: '2026-05-01T10:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
  },
  {
    id: 'lead-2',
    company_id: 'company-1',
    company_name: 'Agence Immobilière Voltaire',
    sector: 'Immobilier',
    city: 'Paris 11e',
    email: 'agence@voltaire-immo.fr',
    phone: '01 55 66 77 88',
    website: null,
    source: 'google_maps',
    ai_score: 72,
    probable_need: 'Nettoyage bureaux 2x/semaine',
    status: 'a_contacter',
    notes: 'Appelez le matin',
    converted_opportunity_id: null,
    created_at: '2026-05-05T10:00:00Z',
    updated_at: '2026-05-05T10:00:00Z',
  },
  {
    id: 'lead-3',
    company_id: 'company-1',
    company_name: 'Clinique Vétérinaire du Marais',
    sector: 'Santé animale',
    city: 'Paris 3e',
    email: 'contact@vetmarais.fr',
    phone: '01 48 87 65 43',
    website: 'www.vetmarais.fr',
    source: 'referral',
    ai_score: 91,
    probable_need: 'Nettoyage et désinfection quotidien',
    status: 'contacte',
    notes: 'Très intéressé, envoyer devis',
    converted_opportunity_id: null,
    created_at: '2026-05-08T10:00:00Z',
    updated_at: '2026-05-08T10:00:00Z',
  },
]

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    company_id: 'company-1',
    lead_id: null,
    client_id: null,
    site_id: null,
    title: 'Nettoyage bureaux - Tech Solutions',
    prospect_name: 'Tech Solutions SARL',
    contact_name: 'Marc Dubois',
    email: 'marc@techsolutions.fr',
    phone: '06 11 22 33 44',
    city: 'Paris 9e',
    site_address: '12 Rue de la Paix, Paris',
    client_type: 'entreprise',
    service_type: 'nettoyage_bureaux',
    estimated_amount: 2400,
    stage: 'proposition' as const,
    next_action_date: '2026-05-20T09:00:00Z',
    notes: 'Attente retour devis',
    status: 'ouvert',
    contact_role: null,
    postal_code: null,
    next_action_type: null,
    next_action_note: null,
    siren: null,
    siret: null,
    naf_code: null,
    legal_form: null,
    company_status: null,
    source: 'manual',
    converted_to_client: false,
    converted_at: null,
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
  },
  {
    id: 'opp-2',
    company_id: 'company-1',
    lead_id: 'lead-1',
    client_id: null,
    site_id: null,
    title: 'Nettoyage cuisine - Le Gourmet',
    prospect_name: 'Restaurant Le Gourmet',
    contact_name: 'Antoine Lebrun',
    email: 'contact@legourmet.fr',
    phone: '01 42 33 44 55',
    city: 'Paris 2e',
    site_address: '8 Rue Montorgueil, Paris',
    client_type: 'professionnel',
    service_type: 'nettoyage_restauration',
    estimated_amount: 1800,
    stage: 'decouverte' as const,
    next_action_date: '2026-05-18T14:00:00Z',
    notes: 'RDV découverte programmé',
    status: 'ouvert',
    contact_role: null,
    postal_code: null,
    next_action_type: null,
    next_action_note: null,
    siren: null,
    siret: null,
    naf_code: null,
    legal_form: null,
    company_status: null,
    source: 'manual',
    converted_to_client: false,
    converted_at: null,
    created_at: '2026-05-12T10:00:00Z',
    updated_at: '2026-05-12T10:00:00Z',
  },
  {
    id: 'opp-3',
    company_id: 'company-1',
    lead_id: null,
    client_id: null,
    site_id: null,
    title: 'Contrat entretien - Résidence Balzac',
    prospect_name: 'Syndic Résidence Balzac',
    contact_name: 'Claire Fontaine',
    email: 'syndic@residencebalzac.fr',
    phone: '01 44 55 66 77',
    city: 'Boulogne-Billancourt',
    site_address: '5 Allée Balzac, Boulogne',
    client_type: 'syndic',
    service_type: 'nettoyage_residence',
    estimated_amount: 3600,
    stage: 'negociation' as const,
    next_action_date: '2026-05-17T10:00:00Z',
    notes: 'Négociation prix en cours',
    status: 'ouvert',
    contact_role: null,
    postal_code: null,
    next_action_type: null,
    next_action_note: null,
    siren: null,
    siret: null,
    naf_code: null,
    legal_form: null,
    company_status: null,
    source: 'manual',
    converted_to_client: false,
    converted_at: null,
    created_at: '2026-05-08T10:00:00Z',
    updated_at: '2026-05-08T10:00:00Z',
  },
  // Opportunité gagnée prête à signer — démontre le flux Yousign mocké
  {
    id: 'opp-4',
    company_id: 'company-1',
    lead_id: null,
    client_id: null,
    site_id: null,
    title: 'Nettoyage open-space - StartupCloud',
    prospect_name: 'StartupCloud',
    contact_name: 'Léa Moreau',
    email: 'lea@startupcloud.io',
    phone: '06 78 90 12 34',
    contact_role: 'CEO',
    city: 'Paris 10e',
    postal_code: '75010',
    site_address: '34 Rue La Fayette, Paris',
    client_type: 'entreprise',
    service_type: 'Nettoyage bureaux + vitres',
    estimated_amount: 4200,
    stage: 'gagne',
    next_action_date: null,
    next_action_type: null,
    next_action_note: null,
    notes: 'Contrat verbalement validé, signature Yousign en attente',
    siren: null,
    siret: null,
    naf_code: null,
    legal_form: null,
    company_status: null,
    source: 'manual',
    status: 'ouvert',
    converted_to_client: false,
    converted_at: null,
    created_at: '2026-05-13T10:00:00Z',
    updated_at: '2026-05-16T10:00:00Z',
  },
]

export const mockSops: Sop[] = [
  {
    id: 'sop-1',
    company_id: 'company-1',
    title: 'Nettoyage bureaux standard',
    service_type: 'nettoyage_bureaux',
    estimated_duration_minutes: 120,
    required_skills: ['nettoyage'],
    required_materials: ['aspirateur', 'balai', 'serpillière'],
    required_products: ['détergent multi-surfaces', 'désinfectant'],
    checklist_items: [
      { id: 'c1', text: 'Vider les corbeilles' },
      { id: 'c2', text: 'Dépoussiérer les bureaux' },
      { id: 'c3', text: 'Aspirer les moquettes' },
      { id: 'c4', text: 'Nettoyer les sanitaires' },
      { id: 'c5', text: 'Passer la serpillière' },
      { id: 'c6', text: 'Nettoyer les vitres intérieures' },
    ],
    safety_instructions: 'Porter des gants. Ventiler lors de l\'utilisation de produits chimiques.',
    notes: null,
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'sop-2',
    company_id: 'company-1',
    title: 'Désinfection cabinet médical',
    service_type: 'nettoyage_medical',
    estimated_duration_minutes: 90,
    required_skills: ['nettoyage', 'désinfection'],
    required_materials: ['chariot de nettoyage', 'sprays'],
    required_products: ['désinfectant hospitalier', 'lingettes virucides'],
    checklist_items: [
      { id: 'c1', text: 'Désinfecter tables d\'examen' },
      { id: 'c2', text: 'Nettoyer et désinfecter sanitaires' },
      { id: 'c3', text: 'Désinfecter poignées de portes' },
      { id: 'c4', text: 'Vider poubelles médicales' },
      { id: 'c5', text: 'Aspirer et serpillière salle attente' },
    ],
    safety_instructions: 'EPI obligatoire : masque FFP2, gants nitrile, sur-chaussures.',
    notes: 'Utiliser uniquement des produits certifiés EN14476',
    created_at: '2026-02-05T10:00:00Z',
    updated_at: '2026-02-05T10:00:00Z',
  },
]

const today = new Date().toISOString().split('T')[0]
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0]
const inThreeDays = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0]
const inFiveDays = new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0]
const inOneWeek = new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0]

export const mockMissions: Mission[] = [
  {
    id: 'mission-1',
    company_id: 'company-1',
    client_id: 'client-1',
    site_id: 'site-1',
    operational_item_id: null,
    service_type: 'nettoyage_bureaux',
    sop_id: 'sop-1',
    status: 'en_cours',
    scheduled_date: today,
    start_time: '08:00',
    planned_hours: 3,
    notes: null,
    priority: 'normale',
    created_at: '2026-05-13T10:00:00Z',
    updated_at: '2026-05-13T10:00:00Z',
    client: mockClients[0],
    site: mockSites[0],
    agents: [mockAgents[0]],
    sop: mockSops[0],
  },
  {
    id: 'mission-2',
    company_id: 'company-1',
    client_id: 'client-2',
    site_id: 'site-3',
    operational_item_id: null,
    service_type: 'nettoyage_medical',
    sop_id: 'sop-2',
    status: 'prevue',
    scheduled_date: today,
    start_time: '18:00',
    planned_hours: 2,
    notes: 'Accès après fermeture cabinet',
    priority: 'haute',
    created_at: '2026-05-13T10:00:00Z',
    updated_at: '2026-05-13T10:00:00Z',
    client: mockClients[1],
    site: mockSites[2],
    agents: [mockAgents[2]],
    sop: mockSops[1],
  },
  {
    id: 'mission-3',
    company_id: 'company-1',
    client_id: 'client-1',
    site_id: 'site-2',
    operational_item_id: null,
    service_type: 'nettoyage_parking',
    sop_id: null,
    status: 'prevue',
    scheduled_date: tomorrow,
    start_time: '07:00',
    planned_hours: 4,
    notes: null,
    priority: 'normale',
    created_at: '2026-05-13T10:00:00Z',
    updated_at: '2026-05-13T10:00:00Z',
    client: mockClients[0],
    site: mockSites[1],
    agents: [mockAgents[1], mockAgents[2]],
    sop: undefined,
  },
  // Mission en cours d'organisation (suite à un contrat signé)
  {
    id: 'mission-4',
    company_id: 'company-1',
    client_id: 'client-1',
    site_id: 'site-2',
    operational_item_id: null,
    service_type: 'Nettoyage parking',
    sop_id: null,
    status: 'prevue',
    operational_status: 'a_organiser',
    scheduled_date: inOneWeek,
    start_time: null,
    planned_hours: 4,
    notes: 'Contrat fraîchement signé — à organiser',
    priority: 'normale',
    urgency: 'normale',
    recurrence: 'mensuelle',
    estimated_workers: 2,
    estimated_profitability: 480,
    required_machines: [],
    consumables: [],
    equipment: [],
    required_skills: ['parking', 'sols_mecanises'],
    parking_notes: null,
    floor_count: 0,
    organization_step: 0,
    contact_name: 'Marie Petit',
    contact_phone: '01 42 56 78 90',
    created_at: '2026-05-15T09:00:00Z',
    updated_at: '2026-05-15T09:00:00Z',
    client: mockClients[0],
    site: mockSites[1],
    agents: [],
  },
  {
    id: 'mission-5',
    company_id: 'company-1',
    client_id: 'client-2',
    site_id: 'site-3',
    operational_item_id: null,
    service_type: 'Désinfection cabinet médical',
    sop_id: 'sop-2',
    status: 'prevue',
    operational_status: 'en_preparation',
    scheduled_date: inThreeDays,
    start_time: null,
    planned_hours: 2,
    notes: 'Récurrence à valider',
    priority: 'haute',
    urgency: 'haute',
    recurrence: 'hebdomadaire',
    estimated_workers: 1,
    estimated_profitability: 240,
    required_machines: ['nettoyeur vapeur'],
    consumables: ['désinfectant médical'],
    equipment: ['EPI'],
    required_skills: ['medical', 'desinfection'],
    parking_notes: 'Parking visiteurs côté est',
    floor_count: 1,
    organization_step: 2,
    contact_name: 'Dr Bernard',
    contact_phone: '01 45 67 89 12',
    created_at: '2026-05-14T14:00:00Z',
    updated_at: '2026-05-14T14:00:00Z',
    client: mockClients[1],
    site: mockSites[2],
    agents: [],
  },
  {
    id: 'mission-6',
    company_id: 'company-1',
    client_id: 'client-1',
    site_id: 'site-1',
    operational_item_id: null,
    service_type: 'Nettoyage bureaux + vitres',
    sop_id: 'sop-1',
    status: 'prevue',
    operational_status: 'en_attente_validation_client',
    scheduled_date: inFiveDays,
    start_time: '07:30',
    planned_hours: 3,
    notes: 'Créneau proposé au client, en attente de validation',
    priority: 'normale',
    urgency: 'normale',
    recurrence: 'ponctuelle',
    estimated_workers: 2,
    estimated_profitability: 360,
    required_machines: ['perche télescopique'],
    consumables: ['détergent vitres'],
    equipment: [],
    required_skills: ['bureaux', 'vitres'],
    parking_notes: null,
    floor_count: 3,
    organization_step: 4,
    contact_name: 'Sophie Lebrun',
    contact_phone: '01 47 23 45 67',
    created_at: '2026-05-12T11:00:00Z',
    updated_at: '2026-05-14T16:00:00Z',
    client: mockClients[0],
    site: mockSites[0],
    agents: [mockAgents[0], mockAgents[1]],
  },
  {
    id: 'mission-7',
    company_id: 'company-1',
    client_id: 'client-2',
    site_id: 'site-3',
    operational_item_id: null,
    service_type: 'Vitrerie',
    sop_id: null,
    status: 'probleme_signale',
    operational_status: 'incident',
    scheduled_date: today,
    start_time: '10:00',
    planned_hours: 2,
    notes: 'Agent en retard, client mécontent',
    priority: 'urgente',
    urgency: 'urgente',
    recurrence: 'ponctuelle',
    estimated_workers: 1,
    estimated_profitability: 180,
    required_machines: [],
    consumables: [],
    equipment: [],
    required_skills: ['vitres'],
    parking_notes: null,
    floor_count: 1,
    organization_step: 4,
    contact_name: 'Dr Bernard',
    contact_phone: '01 45 67 89 12',
    created_at: '2026-05-10T09:00:00Z',
    updated_at: '2026-05-17T08:30:00Z',
    client: mockClients[1],
    site: mockSites[2],
    agents: [mockAgents[1]],
  },
]

export const mockOperationalItems: OperationalItem[] = [
  {
    id: 'op-1',
    company_id: 'company-1',
    client_id: 'client-1',
    site_id: 'site-1',
    opportunity_id: null,
    source: 'contrat',
    title: 'Nettoyage quotidien - Immeuble Champs-Élysées',
    status: 'en_cours',
    priority: 'haute',
    notes: null,
    converted_to_mission: true,
    mission_id: 'mission-1',
    created_at: '2026-05-01T10:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
    client: mockClients[0],
    site: mockSites[0],
  },
  {
    id: 'op-2',
    company_id: 'company-1',
    client_id: 'client-2',
    site_id: 'site-3',
    opportunity_id: null,
    source: 'contrat',
    title: 'Désinfection cabinet - soir',
    status: 'planifie',
    priority: 'haute',
    notes: 'Accès avec code 9876',
    converted_to_mission: false,
    mission_id: null,
    created_at: '2026-05-05T10:00:00Z',
    updated_at: '2026-05-05T10:00:00Z',
    client: mockClients[1],
    site: mockSites[2],
  },
  {
    id: 'op-3',
    company_id: 'company-1',
    client_id: 'client-1',
    site_id: 'site-2',
    opportunity_id: null,
    source: 'demande_client',
    title: 'Nettoyage parking mensuel',
    status: 'a_organiser',
    priority: 'normale',
    notes: 'À planifier avant fin du mois',
    converted_to_mission: false,
    mission_id: null,
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
    client: mockClients[0],
    site: mockSites[1],
  },
]

export const mockTimeEntries: TimeEntry[] = [
  {
    id: 'te-1',
    company_id: 'company-1',
    mission_id: 'mission-1',
    agent_id: 'agent-1',
    client_id: 'client-1',
    site_id: 'site-1',
    date: today,
    planned_hours: 3,
    validated_hours: null,
    hourly_cost: 14,
    total_cost: null,
    status: 'a_valider',
    validated_at: null,
    created_at: '2026-05-13T10:00:00Z',
    updated_at: '2026-05-13T10:00:00Z',
    agent: mockAgents[0],
    mission: mockMissions[0],
    client: mockClients[0],
    site: mockSites[0],
  },
  {
    id: 'te-2',
    company_id: 'company-1',
    mission_id: 'mission-2',
    agent_id: 'agent-3',
    client_id: 'client-2',
    site_id: 'site-3',
    date: today,
    planned_hours: 2,
    validated_hours: null,
    hourly_cost: 15,
    total_cost: null,
    status: 'prevue',
    validated_at: null,
    created_at: '2026-05-13T10:00:00Z',
    updated_at: '2026-05-13T10:00:00Z',
    agent: mockAgents[2],
    mission: mockMissions[1],
    client: mockClients[1],
    site: mockSites[2],
  },
]
